name: DanceRoom2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
    - ultralytics
    - deepface
    - scipy
    - scikit-learn
    - opencv-python
    - tf-keras==2.12.0
    - tensorflow==2.14.1